USE [master]
GO

/****** Object:  Database [RestaurantDatabase]    Script Date: 1/16/2024 7:38:50 AM ******/
CREATE DATABASE [RestaurantDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RestaurantDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER04\MSSQL\DATA\RestaurantDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RestaurantDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER04\MSSQL\DATA\RestaurantDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RestaurantDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RestaurantDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RestaurantDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RestaurantDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RestaurantDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RestaurantDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [RestaurantDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [RestaurantDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RestaurantDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RestaurantDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RestaurantDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RestaurantDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RestaurantDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RestaurantDatabase] SET QUERY_STORE = ON
GO

ALTER DATABASE [RestaurantDatabase] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [RestaurantDatabase] SET  READ_WRITE 
GO

